export const BASE_URL = 'https://upayments-studycase-api.herokuapp.com';
export const Token =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiaGlyYW1hcmVkZHkwNEBnbWFpbC5jb20iLCJnaXRodWIiOiJodHRwczovL2dpdGh1Yi5jb20vYWJoaXJhbWFyZWRkeTIwIiwiaWF0IjoxNjYxNTgxMjAxLCJleHAiOjE2NjIwMTMyMDF9.XMyAQJ0yGPhHREsugnFnyNMksatRgW79Vr0p4igYyak';
